### ISSUE TITLE
Does it work in PHP7.3

### ISSUE THREAD

**Issue by mikk150** [alexeevdv/php-segfault-exception#1]
Based on tests, I have no idea if it works in PHP7.3 which comes out soon.. I do not know if I can use it on production because I hope to migrate my services to PHP7.3 ASAP

**Comment by alexeevdv** [comment]
Adjusted tests to check if real segfault is happened. Tests are passed for PHP7.3RC1 
Also added tests for 5.4 and 5.5 so you could use this production ready solution in your old projects too

https://travis-ci.org/alexeevdv/php-segfault-exception/builds/435524422

Feel free to migrate to 7.3 and deploy it via FTP to shared hosting ASAP!
